
server:
  port: 80
management:
  security:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/medicine?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    type : com.alibaba.druid.pool.DruidDataSource
    username :  root
    password :  123456
    driverClassName : com.mysql.jdbc.Driver

  redis:
    host: 47.106.119.122
    port: 6379
    database: 0
    timeout: 6000  # 连接超时时长（毫秒）

  freemarker:
    template-loader-path: classpath:/templates
    request-context-attribute: request
    http:
    multipart:
      max-file-size: 200MB
interval:
  log:
    time: true  #是否开启日志计时,默认开启
  jwt:
    secret: secret
    expire: 720000
    header: TOKEN
  server:
    domain: http://yhytxh.cn
  weixin:
    appid: wxf3a4806b22d2a7a7 #微信appID
    mchId: 1529299931 #微信商户号
    apiKey: B7BDD1897A4278B5019E23EA682C5857
logging:
  level :
    com.interval : DEBUG
    root : INFO
  config: classpath:logback-spring.xml

